[project]
name = "web"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
  "mkdocs-awesome-pages-plugin==2.10.1",
  "mkdocs-git-revision-date-plugin==0.3.2",
  "mkdocs-material==9.6.3",
]
