production:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    quiz: <%= ENV['XIKOLO_SERVICE_QUIZ'] || 'http://localhost:3800' %>
    submission: <%= ENV['XIKOLO_SERVICE_QUIZ'] || 'http://localhost:3800' %>

development:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    quiz: <%= ENV['XIKOLO_SERVICE_QUIZ'] || 'http://localhost:3800' %>
    submission: <%= ENV['XIKOLO_SERVICE_QUIZ'] || 'http://localhost:3800' %>

test:
  services:
    account: http://web.xikolo.tld/account_service
    course: http://course.xikolo.tld
    quiz: http://quiz.xikolo.tld
    submission: http://quiz.xikolo.tld
