production:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    news: <%= ENV['XIKOLO_SERVICE_NEWS'] || 'http://localhost:4300' %>

development:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    news: <%= ENV['XIKOLO_SERVICE_NEWS'] || 'http://localhost:4300' %>

test:
  services:
    account: http://web.xikolo.tld/account_service
    course: http://course.xikolo.tld
    news: http://news.xikolo.tld
