s3:
  connect_info:
    endpoint: http://s3.xikolo.de
    region: default
    access_key_id: access_key
    secret_access_key: secret_access_key
    force_path_style: true
  buckets:
    uploads: xikolo-uploads
    news: xikolo-public
