production:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    collabspace: <%= ENV['XIKOLO_SERVICE_LEARNING_ROOM'] || 'http://localhost:4800' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    grouping: <%= ENV['XIKOLO_SERVICE_GROUPING'] || 'http://localhost:5600' %>
    learnanalytics: <%= ENV['XIKOLO_SERVICE_LANALYTICS'] || 'http://localhost:5900' %>
    learning_room: <%= ENV['XIKOLO_SERVICE_LEARNING_ROOM'] || 'http://localhost:4800' %>
    news: <%= ENV['XIKOLO_SERVICE_NEWS'] || 'http://localhost:4300' %>
    notification: <%= ENV['XIKOLO_SERVICE_NOTIFICATION'] || 'http://localhost:3200' %>
    peerassessment: <%= ENV['XIKOLO_SERVICE_PEERASSESSMENT'] || 'http://localhost:5400' %>
    pinboard: <%= ENV['XIKOLO_SERVICE_PINBOARD'] || 'http://localhost:3500' %>

development:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    collabspace: <%= ENV['XIKOLO_SERVICE_LEARNING_ROOM'] || 'http://localhost:4800' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    grouping: <%= ENV['XIKOLO_SERVICE_GROUPING'] || 'http://localhost:5600' %>
    learnanalytics: <%= ENV['XIKOLO_SERVICE_LANALYTICS'] || 'http://localhost:5900' %>
    learning_room: <%= ENV['XIKOLO_SERVICE_LEARNING_ROOM'] || 'http://localhost:4800' %>
    news: <%= ENV['XIKOLO_SERVICE_NEWS'] || 'http://localhost:4300' %>
    notification: <%= ENV['XIKOLO_SERVICE_NOTIFICATION'] || 'http://localhost:3200' %>
    peerassessment: <%= ENV['XIKOLO_SERVICE_PEERASSESSMENT'] || 'http://localhost:5400' %>
    pinboard: <%= ENV['XIKOLO_SERVICE_PINBOARD'] || 'http://localhost:3500' %>

test:
  services:
    account: http://localhost:3100
    collabspace: http://localhost:4800
    course: http://localhost:3300
    grouping: http://localhost:5600
    learnanalytics: http://localhost:5900
    learning_room: http://localhost:4800
    news: http://localhost:4300
    notification: http://notification.xikolo.tld/
    peerassessment: http://localhost:5400
    pinboard: http://localhost:3500
