csp:
  enabled: false
locales:
  available: [de, en]
  default: en
s3:
  buckets:
    avatars: xikolo-public
    banners: xikolo-public
    certificate: xikolo-certificate
    course: xikolo-public
    lti: xikolo-public
    pages: xikolo-public
    quiz: xikolo-quiz
    uploads: xikolo-uploads
    video: xikolo-video
    pinboard: xikolo-pinboard
    news: xikolo-public
    scientist: xikolo-scientist
  client:
    endpoint: https://s3.xikolo.de
    region: default
    access_key_id: access_key
    secret_access_key: secret_access_key
    force_path_style: true
  connect_info:
    endpoint: https://s3.xikolo.de
    region: default
    access_key_id: access_key
    secret_access_key: secret_access_key
    force_path_style: true
portal_api:
  enabled: true
  realm: test-realm
transpipe:
  enabled: false
  realm: test-realm
