production:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    collabspace: <%= ENV['XIKOLO_SERVICE_COLLABSPACE'] || 'http://localhost:4800' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    grouping: <%= ENV['XIKOLO_SERVICE_GROUPING'] || 'http://localhost:5600' %>
    notification: <%= ENV['XIKOLO_SERVICE_NOTIFICATION'] || 'http://localhost:3200' %>
    peerassessment: <%= ENV['XIKOLO_SERVICE_PEERASSESSMENT'] || 'http://localhost:5400' %>
    pinboard: <%= ENV['XIKOLO_SERVICE_PINBOARD'] || 'http://localhost:3500' %>

development: &dev
  services: &devserv
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3100' %>
    collabspace: <%= ENV['XIKOLO_SERVICE_COLLABSPACE'] || 'http://localhost:4800' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    grouping: <%= ENV['XIKOLO_SERVICE_GROUPING'] || 'http://localhost:5600' %>
    notification: <%= ENV['XIKOLO_SERVICE_NOTIFICATION'] || 'http://localhost:3200' %>
    peerassessment: <%= ENV['XIKOLO_SERVICE_PEERASSESSMENT'] || 'http://localhost:5400' %>
    pinboard: <%= ENV['XIKOLO_SERVICE_PINBOARD'] || 'http://localhost:3500' %>

test:
  services:
    <<: *devserv
    collabspace: http://collabspace.xikolo.tld
    course: http://course.xikolo.tld
    learning_room: http://collabspace.xikolo.tld
    notification: http://notification.xikolo.tld
