production:
  services:
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    quiz: <%= ENV['XIKOLO_SERVICE_QUIZ'] || 'http://localhost:3800' %>

development: &dev
  services:
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3000/course_service' %>
    quiz: <%= ENV['XIKOLO_SERVICE_QUIZ'] || 'http://localhost:3000/quiz_service' %>

test:
  services:
    course: http://web.xikolo.tld/course_service
    quiz: http://web.xikolo.tld/quiz_service
