production:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3000/account_service' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    notification: <%= ENV['XIKOLO_SERVICE_NOTIFICATION'] || 'http://localhost:3200' %>
    pinboard: <%= ENV['XIKOLO_SERVICE_PINBOARD'] || 'http://localhost:3500' %>

development:
  services:
    account: <%= ENV['XIKOLO_SERVICE_ACCOUNT'] || 'http://localhost:3000/account_service' %>
    course: <%= ENV['XIKOLO_SERVICE_COURSE'] || 'http://localhost:3300' %>
    notification: <%= ENV['XIKOLO_SERVICE_NOTIFICATION'] || 'http://localhost:3200' %>
    pinboard: <%= ENV['XIKOLO_SERVICE_PINBOARD'] || 'http://localhost:3500' %>

test:
  services:
    account: http://web.xikolo.tld/account_service
    course: http://course.xikolo.tld
    notification: http://notification.xikolo.tld
    pinboard: http://pinboard.xikolo.tld
